id: P49C85826
initial_creation_type: input
source_metadata:
  Title: Chandoratnākaraḥ (svopajña samanvitaḥ)
  Editor: Losang Norbu Shastri,
  Publisher: Central Institute of Higher Tibetan Studies
  Place of Publication: Sarnath
  Year: '1990'
  Chandoratnākaraḥ (svopajña samanvitaḥ):
    Text Version: Romanized
    Input Personnel: Milan Shakya
    Input Date: '2013'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of the Exact Methods
    Sponsor: University of the West
created_at: '2022-03-08T16:18:49.809739'
last_modified_at: '2022-03-08T16:18:49.809749'
